print("Welcome to the tip calculator.")
total = float(input("What was the total bill? $"))
tip_per = int(input("What percentage tip would you like to give? 10,12, or 15? "))
person = int(input("How many people to split the bill? "))
bill_tip = total + ((total*tip_per)/100)
bill_person = round((bill_tip/person),2)
print(f"Each person should pay: ${bill_person}")